name: sml_p2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pillow
  - tqdm
  - pyyaml
  - scikit-learn
  - jupyter
  - ipykernel
  - pip:
      - torch>=2.1
      - torchvision>=0.16
      - albumentations>=1.4
      - opencv-python-headless
      - tensorboard
